version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./src:/var/www/html/crud/
    ports:
      - "8070:8070"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/crud
    ports:
      - "9001:9003"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: pericao
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: spotifaux
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: