version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html/crud/
    ports:
      - "8070:8070"
    depends_on:
      - php
    networks:
     - orm-network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/crud
    ports:
      - "9001:9003"
    networks:
     - orm-network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
     - orm-network

volumes:
  pgdata:

networks:
  orm-network:
    driver: bridge