  services:
    vault:
        image: hashicorp/vault:latest
        ports:
          - "8200:8200"
        environment:
          VAULT_API_ADDR: "http://localhost:8200" 
        cap_add:
          - IPC_LOCK
        volumes:
          - ./vault/config/vault-config.hcl:/vault/config/vault-config.hcl
          - vault-data:/vault/file
        command: "vault server -config=/vault/config/vault-config.hcl"
    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: thalis
        RABBITMQ_DEFAULT_PASS: fuck
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq

    minio:
      image: minio/minio
      container_name: minio
      ports:
        - "9000:9000"  # Porta da API S3
        - "9002:9001"  # Porta para o console web
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
      volumes:
        - minio_data:/data
      command: server /data --console-address ":9001"
    nginx:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./src:/var/www/html/crud/
      ports:
        - "8070:8070"
      depends_on:
        - php
      networks:
      - orm-network

    php:
      build:
        context: .
        dockerfile: Dockerfile.php
      volumes:
        - .:/var/www/html/crud
      ports:
        - "9001:9003"
      networks:
      - orm-network

    postgres:
      image: postgres:latest
      container_name: postgres_db
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
      - orm-network
      #command: ["postgres", "-c", "max_connections=200"]

  volumes:
    pgdata:
    vault-data:
    rabbitmq_data:
    minio_data:

  networks:
    orm-network:
      driver: bridge