version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    volumes:
      - ./src:/var/www/html/crud
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.1-fpm   
    volumes:
      - ./src:/var/www/html/crud
